/*
 * Gotify REST-API.
 * This is the documentation of the Gotify REST-API.  # Authentication In Gotify there are two token types: __clientToken__: a client is something that receives message and manages stuff like creating new tokens or delete messages. (f.ex this token should be used for an android app) __appToken__: an application is something that sends messages (f.ex. this token should be used for a shell script)  The token can be transmitted in a header named `X-Gotify-Key`, in a query parameter named `token` or through a header named `Authorization` with the value prefixed with `Bearer` (Ex. `Bearer randomtoken`). There is also the possibility to authenticate through basic auth, this should only be used for creating a clientToken.  \\---  Found a bug or have some questions? [Create an issue on GitHub](https://github.com/gotify/server/issues)
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.gotify.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

/**
 * Params allowed to create or update Applications.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.19.0")
public class ApplicationParams {
  public static final String SERIALIZED_NAME_DEFAULT_PRIORITY = "defaultPriority";
  @SerializedName(SERIALIZED_NAME_DEFAULT_PRIORITY)
  @javax.annotation.Nullable
  private Long defaultPriority;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  @javax.annotation.Nullable
  private String description;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @javax.annotation.Nonnull
  private String name;

  public static final String SERIALIZED_NAME_SORT_KEY = "sortKey";
  @SerializedName(SERIALIZED_NAME_SORT_KEY)
  @javax.annotation.Nullable
  private String sortKey;

  public ApplicationParams() {
  }

  public ApplicationParams defaultPriority(@javax.annotation.Nullable Long defaultPriority) {
    
    this.defaultPriority = defaultPriority;
    return this;
  }

  /**
   * The default priority of messages sent by this application. Defaults to 0.
   * @return defaultPriority
   */
  @javax.annotation.Nullable

  public Long getDefaultPriority() {
    return defaultPriority;
  }


  public void setDefaultPriority(@javax.annotation.Nullable Long defaultPriority) {
    this.defaultPriority = defaultPriority;
  }

  public ApplicationParams description(@javax.annotation.Nullable String description) {
    
    this.description = description;
    return this;
  }

  /**
   * The description of the application.
   * @return description
   */
  @javax.annotation.Nullable

  public String getDescription() {
    return description;
  }


  public void setDescription(@javax.annotation.Nullable String description) {
    this.description = description;
  }

  public ApplicationParams name(@javax.annotation.Nonnull String name) {
    
    this.name = name;
    return this;
  }

  /**
   * The application name. This is how the application should be displayed to the user.
   * @return name
   */
  @javax.annotation.Nonnull

  public String getName() {
    return name;
  }


  public void setName(@javax.annotation.Nonnull String name) {
    this.name = name;
  }

  public ApplicationParams sortKey(@javax.annotation.Nullable String sortKey) {
    
    this.sortKey = sortKey;
    return this;
  }

  /**
   * The sortKey for the application. Uses fractional indexing.
   * @return sortKey
   */
  @javax.annotation.Nullable

  public String getSortKey() {
    return sortKey;
  }


  public void setSortKey(@javax.annotation.Nullable String sortKey) {
    this.sortKey = sortKey;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApplicationParams applicationParams = (ApplicationParams) o;
    return Objects.equals(this.defaultPriority, applicationParams.defaultPriority) &&
        Objects.equals(this.description, applicationParams.description) &&
        Objects.equals(this.name, applicationParams.name) &&
        Objects.equals(this.sortKey, applicationParams.sortKey);
  }

  @Override
  public int hashCode() {
    return Objects.hash(defaultPriority, description, name, sortKey);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApplicationParams {\n");
    sb.append("    defaultPriority: ").append(toIndentedString(defaultPriority)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    sortKey: ").append(toIndentedString(sortKey)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

