/*
 * Gotify REST-API.
 * This is the documentation of the Gotify REST-API.  # Authentication In Gotify there are two token types: __clientToken__: a client is something that receives message and manages stuff like creating new tokens or delete messages. (f.ex this token should be used for an android app) __appToken__: an application is something that sends messages (f.ex. this token should be used for a shell script)  The token can be transmitted in a header named `X-Gotify-Key`, in a query parameter named `token` or through a header named `Authorization` with the value prefixed with `Bearer` (Ex. `Bearer randomtoken`). There is also the possibility to authenticate through basic auth, this should only be used for creating a clientToken.  \\---  Found a bug or have some questions? [Create an issue on GitHub](https://github.com/gotify/server/issues)
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.gotify.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

/**
 * ElevateRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.19.0")
public class ElevateRequest {
  public static final String SERIALIZED_NAME_DURATION_SECONDS = "durationSeconds";
  @SerializedName(SERIALIZED_NAME_DURATION_SECONDS)
  @javax.annotation.Nonnull
  private Long durationSeconds;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nonnull
  private Long id;

  public ElevateRequest() {
  }

  public ElevateRequest durationSeconds(@javax.annotation.Nonnull Long durationSeconds) {
    
    this.durationSeconds = durationSeconds;
    return this;
  }

  /**
   * How long the elevation should last, in seconds.
   * @return durationSeconds
   */
  @javax.annotation.Nonnull

  public Long getDurationSeconds() {
    return durationSeconds;
  }


  public void setDurationSeconds(@javax.annotation.Nonnull Long durationSeconds) {
    this.durationSeconds = durationSeconds;
  }

  public ElevateRequest id(@javax.annotation.Nonnull Long id) {
    
    this.id = id;
    return this;
  }

  /**
   * The client ID to elevate.
   * @return id
   */
  @javax.annotation.Nonnull

  public Long getId() {
    return id;
  }


  public void setId(@javax.annotation.Nonnull Long id) {
    this.id = id;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ElevateRequest elevateRequest = (ElevateRequest) o;
    return Objects.equals(this.durationSeconds, elevateRequest.durationSeconds) &&
        Objects.equals(this.id, elevateRequest.id);
  }

  @Override
  public int hashCode() {
    return Objects.hash(durationSeconds, id);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ElevateRequest {\n");
    sb.append("    durationSeconds: ").append(toIndentedString(durationSeconds)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

