/*
 * Gotify REST-API.
 * This is the documentation of the Gotify REST-API.  # Authentication In Gotify there are two token types: __clientToken__: a client is something that receives message and manages stuff like creating new tokens or delete messages. (f.ex this token should be used for an android app) __appToken__: an application is something that sends messages (f.ex. this token should be used for a shell script)  The token can be transmitted in a header named `X-Gotify-Key`, in a query parameter named `token` or through a header named `Authorization` with the value prefixed with `Bearer` (Ex. `Bearer randomtoken`). There is also the possibility to authenticate through basic auth, this should only be used for creating a clientToken.  \\---  Found a bug or have some questions? [Create an issue on GitHub](https://github.com/gotify/server/issues)
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.gotify.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

/**
 * GotifyInfo Model
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.19.0")
public class GotifyInfo {
  public static final String SERIALIZED_NAME_OIDC = "oidc";
  @SerializedName(SERIALIZED_NAME_OIDC)
  @javax.annotation.Nonnull
  private Boolean oidc;

  public static final String SERIALIZED_NAME_REGISTER = "register";
  @SerializedName(SERIALIZED_NAME_REGISTER)
  @javax.annotation.Nonnull
  private Boolean register;

  public static final String SERIALIZED_NAME_VERSION = "version";
  @SerializedName(SERIALIZED_NAME_VERSION)
  @javax.annotation.Nonnull
  private String version;

  public GotifyInfo() {
  }

  public GotifyInfo oidc(@javax.annotation.Nonnull Boolean oidc) {
    
    this.oidc = oidc;
    return this;
  }

  /**
   * If oidc is enabled.
   * @return oidc
   */
  @javax.annotation.Nonnull

  public Boolean getOidc() {
    return oidc;
  }


  public void setOidc(@javax.annotation.Nonnull Boolean oidc) {
    this.oidc = oidc;
  }

  public GotifyInfo register(@javax.annotation.Nonnull Boolean register) {
    
    this.register = register;
    return this;
  }

  /**
   * If registration is enabled.
   * @return register
   */
  @javax.annotation.Nonnull

  public Boolean getRegister() {
    return register;
  }


  public void setRegister(@javax.annotation.Nonnull Boolean register) {
    this.register = register;
  }

  public GotifyInfo version(@javax.annotation.Nonnull String version) {
    
    this.version = version;
    return this;
  }

  /**
   * The current version.
   * @return version
   */
  @javax.annotation.Nonnull

  public String getVersion() {
    return version;
  }


  public void setVersion(@javax.annotation.Nonnull String version) {
    this.version = version;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GotifyInfo gotifyInfo = (GotifyInfo) o;
    return Objects.equals(this.oidc, gotifyInfo.oidc) &&
        Objects.equals(this.register, gotifyInfo.register) &&
        Objects.equals(this.version, gotifyInfo.version);
  }

  @Override
  public int hashCode() {
    return Objects.hash(oidc, register, version);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GotifyInfo {\n");
    sb.append("    oidc: ").append(toIndentedString(oidc)).append("\n");
    sb.append("    register: ").append(toIndentedString(register)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

