/*
 * Gotify REST-API.
 * This is the documentation of the Gotify REST-API.  # Authentication In Gotify there are two token types: __clientToken__: a client is something that receives message and manages stuff like creating new tokens or delete messages. (f.ex this token should be used for an android app) __appToken__: an application is something that sends messages (f.ex. this token should be used for a shell script)  The token can be transmitted in a header named `X-Gotify-Key`, in a query parameter named `token` or through a header named `Authorization` with the value prefixed with `Bearer` (Ex. `Bearer randomtoken`). There is also the possibility to authenticate through basic auth, this should only be used for creating a clientToken.  \\---  Found a bug or have some questions? [Create an issue on GitHub](https://github.com/gotify/server/issues)
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.gotify.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.Map;

/**
 * The MessageExternal holds information about a message which was sent by an Application.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.19.0")
public class Message {
  public static final String SERIALIZED_NAME_APPID = "appid";
  @SerializedName(SERIALIZED_NAME_APPID)
  @javax.annotation.Nonnull
  private Long appid;

  public static final String SERIALIZED_NAME_DATE = "date";
  @SerializedName(SERIALIZED_NAME_DATE)
  @javax.annotation.Nonnull
  private OffsetDateTime date;

  public static final String SERIALIZED_NAME_EXTRAS = "extras";
  @SerializedName(SERIALIZED_NAME_EXTRAS)
  @javax.annotation.Nullable
  private Map<String, Object> extras = new HashMap<>();

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nonnull
  private Long id;

  public static final String SERIALIZED_NAME_MESSAGE = "message";
  @SerializedName(SERIALIZED_NAME_MESSAGE)
  @javax.annotation.Nonnull
  private String message;

  public static final String SERIALIZED_NAME_PRIORITY = "priority";
  @SerializedName(SERIALIZED_NAME_PRIORITY)
  @javax.annotation.Nullable
  private Long priority;

  public static final String SERIALIZED_NAME_TITLE = "title";
  @SerializedName(SERIALIZED_NAME_TITLE)
  @javax.annotation.Nullable
  private String title;

  public Message() {
  }
  /**
   * Constructor with only readonly parameters
   */
  
  public Message(
     Long appid, 
     OffsetDateTime date, 
     Long id
  ) {
    this();
    this.appid = appid;
    this.date = date;
    this.id = id;
  }

  /**
   * The application id that send this message.
   * @return appid
   */
  @javax.annotation.Nonnull

  public Long getAppid() {
    return appid;
  }



  /**
   * The date the message was created.
   * @return date
   */
  @javax.annotation.Nonnull

  public OffsetDateTime getDate() {
    return date;
  }



  public Message extras(@javax.annotation.Nullable Map<String, Object> extras) {
    
    this.extras = extras;
    return this;
  }

  public Message putExtrasItem(String key, Object extrasItem) {
    if (this.extras == null) {
      this.extras = new HashMap<>();
    }
    this.extras.put(key, extrasItem);
    return this;
  }

  /**
   * The extra data sent along the message.  The extra fields are stored in a key-value scheme. Only accepted in CreateMessage requests with application/json content-type.  The keys should be in the following format: &amp;lt;top-namespace&amp;gt;::[&amp;lt;sub-namespace&amp;gt;::]&amp;lt;action&amp;gt;  These namespaces are reserved and might be used in the official clients: gotify android ios web server client. Do not use them for other purposes.
   * @return extras
   */
  @javax.annotation.Nullable

  public Map<String, Object> getExtras() {
    return extras;
  }


  public void setExtras(@javax.annotation.Nullable Map<String, Object> extras) {
    this.extras = extras;
  }

  /**
   * The message id.
   * @return id
   */
  @javax.annotation.Nonnull

  public Long getId() {
    return id;
  }



  public Message message(@javax.annotation.Nonnull String message) {
    
    this.message = message;
    return this;
  }

  /**
   * The message. Markdown (excluding html) is allowed.
   * @return message
   */
  @javax.annotation.Nonnull

  public String getMessage() {
    return message;
  }


  public void setMessage(@javax.annotation.Nonnull String message) {
    this.message = message;
  }

  public Message priority(@javax.annotation.Nullable Long priority) {
    
    this.priority = priority;
    return this;
  }

  /**
   * The priority of the message. If unset, then the default priority of the application will be used.
   * @return priority
   */
  @javax.annotation.Nullable

  public Long getPriority() {
    return priority;
  }


  public void setPriority(@javax.annotation.Nullable Long priority) {
    this.priority = priority;
  }

  public Message title(@javax.annotation.Nullable String title) {
    
    this.title = title;
    return this;
  }

  /**
   * The title of the message.
   * @return title
   */
  @javax.annotation.Nullable

  public String getTitle() {
    return title;
  }


  public void setTitle(@javax.annotation.Nullable String title) {
    this.title = title;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Message message = (Message) o;
    return Objects.equals(this.appid, message.appid) &&
        Objects.equals(this.date, message.date) &&
        Objects.equals(this.extras, message.extras) &&
        Objects.equals(this.id, message.id) &&
        Objects.equals(this.message, message.message) &&
        Objects.equals(this.priority, message.priority) &&
        Objects.equals(this.title, message.title);
  }

  @Override
  public int hashCode() {
    return Objects.hash(appid, date, extras, id, message, priority, title);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Message {\n");
    sb.append("    appid: ").append(toIndentedString(appid)).append("\n");
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("    extras: ").append(toIndentedString(extras)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    priority: ").append(toIndentedString(priority)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

