/*
 * Gotify REST-API.
 * This is the documentation of the Gotify REST-API.  # Authentication In Gotify there are two token types: __clientToken__: a client is something that receives message and manages stuff like creating new tokens or delete messages. (f.ex this token should be used for an android app) __appToken__: an application is something that sends messages (f.ex. this token should be used for a shell script)  The token can be transmitted in a header named `X-Gotify-Key`, in a query parameter named `token` or through a header named `Authorization` with the value prefixed with `Bearer` (Ex. `Bearer randomtoken`). There is also the possibility to authenticate through basic auth, this should only be used for creating a clientToken.  \\---  Found a bug or have some questions? [Create an issue on GitHub](https://github.com/gotify/server/issues)
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.gotify.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

/**
 * Used to exchange an authorization code for a gotify client token.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.19.0")
public class OIDCExternalTokenRequest {
  public static final String SERIALIZED_NAME_CODE = "code";
  @SerializedName(SERIALIZED_NAME_CODE)
  @javax.annotation.Nonnull
  private String code;

  public static final String SERIALIZED_NAME_CODE_VERIFIER = "code_verifier";
  @SerializedName(SERIALIZED_NAME_CODE_VERIFIER)
  @javax.annotation.Nonnull
  private String codeVerifier;

  public static final String SERIALIZED_NAME_STATE = "state";
  @SerializedName(SERIALIZED_NAME_STATE)
  @javax.annotation.Nonnull
  private String state;

  public OIDCExternalTokenRequest() {
  }

  public OIDCExternalTokenRequest code(@javax.annotation.Nonnull String code) {
    
    this.code = code;
    return this;
  }

  /**
   * The authorization code from the OIDC provider.
   * @return code
   */
  @javax.annotation.Nonnull

  public String getCode() {
    return code;
  }


  public void setCode(@javax.annotation.Nonnull String code) {
    this.code = code;
  }

  public OIDCExternalTokenRequest codeVerifier(@javax.annotation.Nonnull String codeVerifier) {
    
    this.codeVerifier = codeVerifier;
    return this;
  }

  /**
   * The PKCE code verifier.
   * @return codeVerifier
   */
  @javax.annotation.Nonnull

  public String getCodeVerifier() {
    return codeVerifier;
  }


  public void setCodeVerifier(@javax.annotation.Nonnull String codeVerifier) {
    this.codeVerifier = codeVerifier;
  }

  public OIDCExternalTokenRequest state(@javax.annotation.Nonnull String state) {
    
    this.state = state;
    return this;
  }

  /**
   * The state from the authorize response.
   * @return state
   */
  @javax.annotation.Nonnull

  public String getState() {
    return state;
  }


  public void setState(@javax.annotation.Nonnull String state) {
    this.state = state;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OIDCExternalTokenRequest oiDCExternalTokenRequest = (OIDCExternalTokenRequest) o;
    return Objects.equals(this.code, oiDCExternalTokenRequest.code) &&
        Objects.equals(this.codeVerifier, oiDCExternalTokenRequest.codeVerifier) &&
        Objects.equals(this.state, oiDCExternalTokenRequest.state);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, codeVerifier, state);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OIDCExternalTokenRequest {\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    codeVerifier: ").append(toIndentedString(codeVerifier)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

