/*
 * Gotify REST-API.
 * This is the documentation of the Gotify REST-API.  # Authentication In Gotify there are two token types: __clientToken__: a client is something that receives message and manages stuff like creating new tokens or delete messages. (f.ex this token should be used for an android app) __appToken__: an application is something that sends messages (f.ex. this token should be used for a shell script)  The token can be transmitted in a header named `X-Gotify-Key`, in a query parameter named `token` or through a header named `Authorization` with the value prefixed with `Bearer` (Ex. `Bearer randomtoken`). There is also the possibility to authenticate through basic auth, this should only be used for creating a clientToken.  \\---  Found a bug or have some questions? [Create an issue on GitHub](https://github.com/gotify/server/issues)
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.gotify.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

/**
 * Used to initiate the OIDC authorization flow for an external client.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.19.0")
public class OIDCExternalAuthorizeRequest {
  public static final String SERIALIZED_NAME_CODE_CHALLENGE = "code_challenge";
  @SerializedName(SERIALIZED_NAME_CODE_CHALLENGE)
  @javax.annotation.Nonnull
  private String codeChallenge;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @javax.annotation.Nonnull
  private String name;

  public static final String SERIALIZED_NAME_REDIRECT_URI = "redirect_uri";
  @SerializedName(SERIALIZED_NAME_REDIRECT_URI)
  @javax.annotation.Nonnull
  private String redirectUri;

  public OIDCExternalAuthorizeRequest() {
  }

  public OIDCExternalAuthorizeRequest codeChallenge(@javax.annotation.Nonnull String codeChallenge) {
    
    this.codeChallenge = codeChallenge;
    return this;
  }

  /**
   * The PKCE code challenge (S256).
   * @return codeChallenge
   */
  @javax.annotation.Nonnull

  public String getCodeChallenge() {
    return codeChallenge;
  }


  public void setCodeChallenge(@javax.annotation.Nonnull String codeChallenge) {
    this.codeChallenge = codeChallenge;
  }

  public OIDCExternalAuthorizeRequest name(@javax.annotation.Nonnull String name) {
    
    this.name = name;
    return this;
  }

  /**
   * The client name to display in gotify.
   * @return name
   */
  @javax.annotation.Nonnull

  public String getName() {
    return name;
  }


  public void setName(@javax.annotation.Nonnull String name) {
    this.name = name;
  }

  public OIDCExternalAuthorizeRequest redirectUri(@javax.annotation.Nonnull String redirectUri) {
    
    this.redirectUri = redirectUri;
    return this;
  }

  /**
   * The app&#39;s redirect URI.
   * @return redirectUri
   */
  @javax.annotation.Nonnull

  public String getRedirectUri() {
    return redirectUri;
  }


  public void setRedirectUri(@javax.annotation.Nonnull String redirectUri) {
    this.redirectUri = redirectUri;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OIDCExternalAuthorizeRequest oiDCExternalAuthorizeRequest = (OIDCExternalAuthorizeRequest) o;
    return Objects.equals(this.codeChallenge, oiDCExternalAuthorizeRequest.codeChallenge) &&
        Objects.equals(this.name, oiDCExternalAuthorizeRequest.name) &&
        Objects.equals(this.redirectUri, oiDCExternalAuthorizeRequest.redirectUri);
  }

  @Override
  public int hashCode() {
    return Objects.hash(codeChallenge, name, redirectUri);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OIDCExternalAuthorizeRequest {\n");
    sb.append("    codeChallenge: ").append(toIndentedString(codeChallenge)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    redirectUri: ").append(toIndentedString(redirectUri)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

